### ISSUE TITLE
Main Menu

### ISSUE THREAD

**Issue by Venom0us** [Venom0us/Emberpoint#15]
Add a seperate console that shows the main menu with a nice big title 'Emberpoint' in some fancy
ascii characters.

Add a button 'Play' which transitions to the gameplay.
Add a button 'Contributors' which transitions to a seperate menu that shows
a list of all the project contributors.
Add a button 'Options' which will later have a seperate menu for key bindings.
Add a button 'Exit' which closes the application.

**Comment by Smartis2812** [comment]
Question:
Will the player choose his name?
Or are there any sub menus planed?

**Comment by Venom0us** [comment]
No we'll probably stick to some specific character name.
We won't go into too much configuration for the player.

There only 3 major windows:

- Main menu 
- Gameplay
- Game over menu

@Smartis2812
