### ISSUE TITLE
Object/Item interaction system

### ISSUE THREAD

**Issue by Venom0us** [Venom0us/Emberpoint#40]
We need to be able to interact with objects and items.
And have custom actions for each object/item that is interactable.
Should be defined somewhere? Ideas are welcome.

Define some kind of keybinding as interaction key,
When standing near an interactable tile, the player can press this keybinding
and an action is executed.

Visual note: We should show the player that a cell near him is interactable.
Either by showing a small icon with the interaction key glyph or something else.

Linked to: #19

**Comment by Venom0us** [comment]
Maybe the interaction button can also be used to open and close doors, allow player to go onto staircase etc?

**Comment by MattHaluska** [comment]
Hello Venom0us, my friend otogyongyosi would like to take this issue. Yesterday he noticed that he is no longer available to write comments under issues on this project, so he asked me to ask you if he did something wrong.

**Comment by Venom0us** [comment]
> 
> 
> Hello Venom0us, my friend otogyongyosi would like to take this issue. Yesterday he noticed that he is no longer available to write comments under issues on this project, so he asked me to ask you if he did something wrong.

Wasn't sure if it was a real person, I had a similar request from this person months ago and no reactions.

**Comment by otogyongyosi** [comment]
Hello Venom0us, I would like to take care of this issue. As for the last issue, I received an email that it was closed by another issue, so I did not respond.
