### ISSUE TITLE
Add Game Over window

### ISSUE THREAD

**Issue by Venom0us** [Venom0us/Emberpoint#43]
When the entity catches the player, a Game Over window should be shown.
The game over window should just be a big title "Game Over" in fancy ascii.

You can take a look at how the game window is drawn, we will need something similar for this game over window.

- Add button 'Back to the main menu' -> Returns to the main menu
- Add button 'Exit' -> Closes the game application

**Comment by MattHaluska** [comment]
Hello, I would like to take this one.

**Comment by Venom0us** [comment]
> Hello, I would like to take this one.

I'll be waiting for that pull request :), if you have any questions you can ask them here or on gitter.

**Comment by MattHaluska** [comment]
Should it be implemented similar as DialogWindow ?

**Comment by MattHaluska** [comment]
Dialog window should be used for printing 'Back to the main menu' and 'Exit' messages and Map window should be replaced with "Game Over" title.

**Comment by Venom0us** [comment]
It would be easier to make a new GameOverWindow console and add it to the child list of the GameWindow console, then we can disable all consoles except the GameOverWindow when the game over state triggers.

The dialog window currently is on a fixed position and it is right now designed specifically for the Gameplay window.

**Comment by MattHaluska** [comment]
Thank you for your answer. For now everything is clear for me :)

**Comment by MattHaluska** [comment]
Should I draw the "Game Over" title from .txt file ?

**Comment by Venom0us** [comment]
It's fine if you hardcode it into the window, it will only be used once.

**Comment by MattHaluska** [comment]
Allright i will do it that hardcore way :)

**Comment by MattHaluska** [comment]
> 
> 
> Allright i will do it that hardcore way :)

There was a little misunderstanding. So I will do it  the "hardcode" not "hardcore" way :D

**Comment by Venom0us** [comment]
> 
> 
> > Allright i will do it that hardcore way :)
> 
> There was a little misunderstanding. So I will do it the "hardcode" not "hardcore" way :D

Eitherway was good hahahaha

**Comment by MattHaluska** [comment]
Yes, basically it was on point :D

**Comment by MattHaluska** [comment]
Are you good with this font ?  http://patorjk.com/software/taag/#p=display&f=Epic&t=Game%20Over

**Comment by Venom0us** [comment]
Oh yeah sure looks great!

**Comment by Venom0us** [comment]
@MattHaluska if you need some inspiration take a look at my pull request for the main menu: https://github.com/Venom0us/Emberpoint/pull/56

**Comment by MattHaluska** [comment]
I think that i have finished it

**Comment by Venom0us** [comment]
Make a pull request when you're ready, and assign me to review :)

**Comment by Venom0us** [comment]
fixed in #58
