### ISSUE TITLE
Improve map visuals by changing foreground and background colors on certain tiles

### ISSUE THREAD

**Issue by Venom0us** [Venom0us/Emberpoint#64]
Walls and such we can adjust with a different background, to make them stand out from the rest of the tiles. I'm sure we can make more of these kind of improvements on other tiles to make the game more clear to the player where he should go and easier to find the objects he is looking for.

Ideas:

Change wall backgrounds to represent the walls clearer.
Change floor background color for rooms (different per room maybe?)
Change the hallway floor background,

Note:
If we implement new algorithms (eg. to retrieve tiles grouped by room etc)
We should also probably have some kind of test coverage for this?

Make sure that tiles with brightness applied on them are still functional

**Comment by otogyongyosi** [comment]
Hi, I would like to help solve this issue.

**Comment by Venom0us** [comment]
Hi @otogyongyosi, sure you can pick this up. I assigned you this issue.
Let me know if you want any feedback on your progress.
You can also discuss anything you want to add if it's not clear.

**Comment by Venom0us** [comment]
With the merge of recent issue #83 it is now possible to set background colors on cells.
This can be done, by adding the 'background' element to the blueprinttiles.json
which is set up similar to the foreground element.

**Comment by Venom0us** [comment]
> 
> 
> Hi, I would like to help solve this issue.

@otogyongyosi are you actively working on this?

**Comment by agit15** [comment]
I would tackle this issue
