### ISSUE TITLE
Add options menu (keybindings)

### ISSUE THREAD

**Issue by Venom0us** [Venom0us/Emberpoint#67]
In the main menu we have an options button.
This button should load the keybindings console where we can customize our keybindings.

**Comment by rkrawczyszyn** [comment]
Hi @Venom0us 
Are you looking for contributors to any of your projects? I've some spare time recently so maybe I could help? How may I contact you?

**Comment by Venom0us** [comment]
Hello rkrawczyszyn, The Emberpoint project is an opensource project welcome to any and all contributions. You are welcome to pick an issue and work on it or create new issues with ideas and we can discuss them. Let me know if you wanna pick up one of the issues and I'll assign you.
I am available on gitter for chatting.
https://gitter.im/Venom0us/Emberpoint

**Comment by Venom0us** [comment]
> Hi @Venom0us
> Are you looking for contributors to any of your projects? I've some spare time recently so maybe I could help? How may I contact you?
> EDIT: oops, apologies! I read this info later on: https://github.com/Venom0us/Emberpoint/blob/master/CONTRIBUTING.md

Hello rkrawczyszyn, The Emberpoint project is an opensource project welcome to any and all contributions. You are welcome to pick an issue and work on it or create new issues with ideas and we can discuss them. Let me know if you wanna pick up one of the issues and I'll assign you.
I am available on gitter for chatting.
https://gitter.im/Venom0us/Emberpoint
