### ISSUE TITLE
Abstract class Blueprint.cs should be refactored 

### ISSUE THREAD

**Issue by maratmuginov** [Venom0us/Emberpoint#98]
We need to simplify long noodle soups of imperative code like T[] GetCells() to comply with clean code principles.

**Comment by Venom0us** [comment]
If you decide to refactor GetCells method, then make sure to write extra unit tests for Blueprint class.
We definitely need one  that checks if the cells retrieved actually match the blueprint.txt

**Comment by Venom0us** [comment]
Resolved in #118
